#!/bin/bash

TESTS="package control config"

make

if [[ $? != 0 ]]; then exit 1; fi
	

#test amd coverage reports
#for file in `ls *.c`; do
for test in $TESTS; do
	./test-$test
	#have to cd for gcov to find the right one. Or?
	cd ../src
	gcov $test.c
	cd ../test
done

echo 'If you were expecting increased coverage, try a "make clean"'
